uc-cdis/userdatamodel

userdatamodel/models.py, userdatamodel/user.py
- add is_admin boolean field
- remove the length constrain of email field
=> feat(admin): add is_admin field

userdatamodel/models.py
update import accordingly for #5
=> fix(models): update provider import

userdatamodel/models.py, userdatamodel/user.py
r? @thanh-nguyen-dang 
ticket [BN-155](https://uc-cdis.atlassian.net/browse/BN-155)
=> feat(hmac): add hmac keypair table

userdatamodel/user.py
=> feat(debug): add __str__ and __repr__

userdatamodel/user.py
- Previously I had an association proxy between `User` and `Project` linked by UserAccess, this makes us able to access a list of projects a user has access to, but most of the time, we actually want a list of projects with UserAccess.privilege. So a changed the proxy to be a dictionary of { project.auth_id: UserAccess.privilege} [Docs here](http://docs.sqlalchemy.org/en/latest/orm/extensions/associationproxy.html#proxying-to-dictionary-based-collections)
- Created another User.projects association proxy which is a dictionary of {project.auth_id: project}
- I changed Project.dbgap_accession_number to auth_id as we have projects that's not governed by dbgap - this needs manual migration for existing database: `alter table project rename dbgap_accession_number to auth_id;`
- add uniqueness …
=> feat(user): adjust user access association proxy

userdatamodel/driver.py
=> feat(driver): add get_or_create method

userdatamodel/driver.py
add migration script to rename `research_group` to `Group`
=> fix(migration): migrate research_group

userdatamodel/driver.py
should only run migration when the research_group exists
=> fix(migration): fix for empty database

userdatamodel/user.py
`__init__` should pass `_`-prefixed args to `Base.__init__`
=> feat(rbac): fix policy args

userdatamodel/models.py, userdatamodel/user.py
- Remove `policy` tables since these will live in arborist from now on.
=> fix(remove-policy): remove policy table

userdatamodel/models.py, userdatamodel/user.py
=> Revert "fix(remove-policy): remove policy table"

userdatamodel/user.py
Change certificates backref to certificates_uploaded
=> Change certificates backref to certificates_uploaded

setup.py
=> bump sqlalchemy

userdatamodel/user.py
* also added user_audit_logs
- Support Synapse
- Add `user_audit_logs`
=> feat(synapse): add Synapse

userdatamodel/user.py
Sister PR: https://github.com/uc-cdis/fence/pull/767
- Add property on IdentityProvider class to allow Fence-Cognito integration https://github.com/uc-cdis/fence/pull/767
=> feat(cognito): add cognito to IdentityProvider

userdatamodel/user.py
Description about what this pull request does.
Please make sure to follow the [DEV guidelines](https://gen3.org/resources/developer/dev-introduction/) before asking for review.
- Add RAS as identity provider.
=> PXP-6047 add ras as IDP

.pre-commit-config.yaml, .secrets.baseline
Pypi secrets in travis cc @fantix
=> precommit hooks

.secrets.baseline, userdatamodel/user.py
- Optional `authz` column on `Project` table to persist a mapping from `auth_id` to `authz` if necessary
=> feat(authz): add optional authz mapping column to Project table

setup.py
Description about what this pull request does.
Please make sure to follow the [DEV guidelines](https://gen3.org/resources/developer/dev-introduction/) before asking for review.
- Implemented XXX
- ensure setup.py matches requirement file
=> fix(deps): ensure setup.py matches requirement file

.pre-commit-config.yaml, .secrets.baseline, .travis.yml, Pipfile, Pipfile.lock
=> Upgrade python to 3.9
